# This workflow will install Python dependencies and run tests

name: FMS Extras Testing

on: [pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: [gpu]

    steps:
    - uses: actions/checkout@v3
    # - name: Set up Python 3.10
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: "3.10"
    - name: Enable Worker Python
      run: |
        echo "/home/gha/miniforge3/bin/" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python -m venv --system-site-packages .venv
        . ./.venv/bin/activate
        
        # Enables the virtual env for following steps
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        python -m pip install --upgrade pip
        pip install pytest numpy
        pip install transformers==4.35.0
        pip install safetensors
        pip install ibm-fms
        pip install .
        
    - name: Test with pytest
      run: |
        pytest -vv -rP tests/
